[package]
name = "zxibs/game-template"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
ReplicaService = "brittonfischer/replicaservice@^0"
ProfileService = "brittonfischer/profileservice@^2"
RoactSpring = "chriscerie/roact-spring@^0"
RoduxHooks = "solarhorizon/rodux-hooks@^0"
FastCast = "encodedvenom/fastcastredux@^0"
RoactRouter = "reselim/roact-router@^1"
GoodSignal = "stravant/goodsignal@^0"
Janitor = "howmanysmall/janitor@^1"
PartCache = "4igz/partcache@^1"
Promise = "evaera/promise@^3"
Llama = "freddylist/llama@^1"
Matter = "evaera/matter@^0"
Rodux = "roblox/rodux@^3"
Roact = "roblox/roact@^1"
t = "osyrisrblx/t@^3"
